def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('about', '/about')
    config.add_route('logout', '/logout')
    config.add_route('login', '/login')
    config.add_route('oneAdvert', '/oneAdvert/{history_id}')
    config.add_route('user', '/user')
    config.add_route('delete', '/delete/{id}')
    config.add_route('advert', '/advert')
    config.add_route('uslugi', '/uslugi')
    config.add_route('registration', '/registration')
